In [1]:
import os
import sys
newPath = os.path.dirname(os.path.abspath(""))
if newPath not in sys.path:
    sys.path.append(newPath)

from BI import bi
import jax.numpy as jnp
m = bi(platform='cpu')

net = jnp.array([[0, 2, 3, 4],
                [5, 0, 7, 8],
                [9, 10, 0, 12],
                [13, 14, 15, 0]])
net_sym = jnp.array([[0, 2, 3, 4],
                    [2, 0, 7, 8],
                    [3, 7, 0, 12],
                    [ 4, 8,  12, 0]])

vec = jnp.array([1, 2, 3, 4])

jax.local_device_count 32


In [2]:
print(m.net.is_symmetric(net))
print(m.net.is_symmetric(net_sym))

False
True


In [3]:
m.net.vec_to_mat(vec, shape = (4,1))

Array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int64)

In [4]:
print(m.net.get_tri(net, type='upper', diag=0))
print(m.net.get_tri(net, type='upper', diag=1))
print(m.net.get_tri(net, type='lower', diag=0))
print(m.net.get_tri(net, type='lower', diag=1))

[ 0  2  3  4  0  7  8  0 12  0]
[ 2  3  4  7  8 12]
[ 0  5  0  9 10  0 13 14 15  0]
[ 5  9 10 13 14 15]


In [5]:
print(net)
m.net.mat_to_edgl(net)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


Array([[ 2,  5],
       [ 3,  9],
       [ 4, 13],
       [ 7, 10],
       [ 8, 14],
       [12, 15]], dtype=int64)

In [6]:
m.net.edgl_to_mat(m.net.mat_to_edgl(net), 4)

Array([[ 0.,  2.,  3.,  4.],
       [ 5.,  0.,  7.,  8.],
       [ 9., 10.,  0., 12.],
       [13., 14., 15.,  0.]], dtype=float64)

In [7]:
m.net.vec_to_edgl(vec)

Array([[1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4]], dtype=int64)

In [8]:
m.net.vec_node_to_edgle(jnp.stack([vec, vec], axis= 1))

Array([[1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4]], dtype=int64)