In [ ]:
import tensorflow_probability.substrates.jax.distributions as tfd
# Get all names defined in the jnp
all_names = dir(tfd)
# Create a dictionary with all names
class_dict = {name: getattr(tfd, name) for name in all_names}

# Function to create new functions
def create_new_function(class_obj):
    def new_function(sample_shape=(), *args, **kwargs):
        return tfd.Sample(class_obj(*args, **kwargs), sample_shape)
    return new_function

# Create a Python file and write the functions to it
with open("generated_functions.py", "w") as file:
    for key, value in class_dict.items():
        if callable(value):
            try:
                # Create the new function using the class object from class_dict
                func_name = key.lower()
                function_str = f"def {func_name}(sample_shape=(), *args, **kwargs):\n"
                function_str += f"    return root(tfd.Sample({value.__name__}(*args, **kwargs), sample_shape))\n"
                file.write(function_str)
            except Exception as e:
                print(f"Error creating function for {key}: {e}")
        else:
            print(f"Ignoring non-callable object for key {key}: {value}")

# Now all functions have been written to "generated_functions.py"


In [1]:
from generated_functions import*

2024-04-01 12:56:20.909325: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-01 12:56:20.909367: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-01 12:56:20.909868: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-01 12:56:21.347732: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
init_key, sample_key = random.split(random.PRNGKey(int(r.randint(0, 10000000))))
init_key = jnp.array(init_key)

def model():
    a = yield normal(1, 0, 1e6)
    b = yield normal(1, 0, 1e6)
    s = yield normal(1, 0, 1e6)
    y = yield tfd.Independent(
        tfd.Normal(a+b, s), name = 'y'
    )
    
tmp = tfd.JointDistributionCoroutineAutoBatched(model)
tmp.sample(seed=init_key)


An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


StructTuple(
  var0=Array([1316015.4], dtype=float32),
  var1=Array([1263855.1], dtype=float32),
  var2=Array([565713.06], dtype=float32),
  y=Array([2105595.], dtype=float32)
)

In [ ]:
normal()

In [4]:
obs = tfd.Normal(10, 3).sample(20, seed=jnp.array(init_key))
root = tfd.JointDistributionCoroutine.Root
import tensorflow_probability.substrates.jax.distributions as tfd
import random as r
from jax import random
import jax.numpy as jnp
init_key, sample_key = random.split(random.PRNGKey(int(r.randint(0, 10000000))))
def model():
    a = yield normal('a', 1,0,1e6)
    b = yield normal('b', 1,0,1e6)
    s = yield normal('s', 1,0,1e6)
    y = yield tfd.Independent(
        tfd.Normal(a+b*obs, s), name = 'y'
    )    
tmp = tfd.JointDistributionCoroutine(model)
tmp.sample(seed=jnp.array(init_key))


StructTuple(
  a=Array([2016480.5], dtype=float32),
  b=Array([-152975.55], dtype=float32),
  s=Array([196093.52], dtype=float32),
  y=Array([-129115.49,  656726.9 ,  842405.4 ,  108049.67,  427953.66,
            272430.62,  168389.4 ,  335846.5 ,  722380.56,  477951.  ,
            428336.38,  373258.12,  143430.2 ,  849390.6 ,  485359.12,
            555898.6 ,   73203.5 ,  427286.9 ,  533781.5 ,  602774.4 ],      dtype=float32)
)

In [4]:
import pandas as pd
d = pd.read_csv('data/Howell1.csv', sep=';')
d = d[d.age > 18]
#self.df["weight.per.g"].pipe(lambda x: (x - x.mean()) / x.std())
d.weight = d.weight - d.weight.mean()
d.age = d.age - d.age.mean()

def model():
    sigma = yield uniform(1, 0, 50)
    alpha = yield normal(1, 0, 1)
    beta = yield normal(1, 178, 20)
    height = yield Independent(Normal(alpha + beta * jnp.array(d.weight.values, dtype=jnp.float32), sigma))
    
tmp = tfd.JointDistributionCoroutine(model)
r = tmp.sample(seed=jnp.array(init_key))
r._replace(var3=jnp.array(d.height.values))

StructTuple(
  var0=Array([45.295776], dtype=float32),
  var1=Array([1.2638551], dtype=float32),
  var2=Array([189.31425], dtype=float32),
  var3=Array([151.765 , 139.7   , 136.525 , 156.845 , 145.415 , 163.83  ,
           149.225 , 168.91  , 147.955 , 165.1   , 154.305 , 151.13  ,
           144.78  , 149.9   , 150.495 , 163.195 , 157.48  , 143.9418,
           161.29  , 156.21  , 146.4   , 148.59  , 147.32  , 147.955 ,
           161.925 , 146.05  , 146.05  , 152.7048, 142.875 , 142.875 ,
           147.955 , 160.655 , 151.765 , 162.8648, 171.45  , 147.32  ,
           147.955 , 154.305 , 143.51  , 146.7   , 165.735 , 152.4   ,
           141.605 , 158.8   , 155.575 , 164.465 , 151.765 , 161.29  ,
           154.305 , 145.415 , 145.415 , 152.4   , 163.83  , 144.145 ,
           153.67  , 142.875 , 167.005 , 158.4198, 165.735 , 149.86  ,
           154.94  , 160.9598, 161.925 , 147.955 , 159.385 , 148.59  ,
           136.525 , 158.115 , 144.78  , 156.845 , 179.07  , 170.18  ,
      

In [5]:
d = pd.read_csv('data/Howell1.csv', sep=';')
d = d[d.age > 18]
d.weight = d.weight - d.weight.mean()
d.age = d.age - d.age.mean()

def model():
    sigma = yield uniform(1, 0, 50, name = 'sigma')
    alpha_sample = yield normal(1, 0, 1)  # Renamed var1 to alpha_sample
    beta = yield normal(1, 178, 20)
    height = yield Independent(Normal(alpha_sample + beta * jnp.array(d.weight.values, dtype=jnp.float32), sigma))
    
tmp = tfd.JointDistributionCoroutine(model)
r = tmp.sample(seed=jnp.array(init_key))
r


StructTuple(
  var0=Array([45.295776], dtype=float32),
  var1=Array([1.2638551], dtype=float32),
  var2=Array([189.31425], dtype=float32),
  var3=Array([ 5.24895569e+02, -1.65329822e+03, -2.48176660e+03,  1.58646301e+03,
           -6.70531738e+02,  3.39413477e+03, -1.24367114e+03,  1.99619739e+03,
           -1.94112744e+03,  1.83926025e+03,  9.57691467e+02, -7.51466248e+02,
           -1.66698779e+03,  4.66132904e+02, -2.17104761e+03,  6.02172668e+02,
           -5.09897339e+02, -1.23505798e+03,  7.71507629e+02, -4.50738953e+02,
           -1.73380139e+03, -1.31726465e+03, -1.74052283e+03, -8.75049622e+02,
            1.93978125e+03, -1.41244812e+03, -1.18915674e+03,  2.20680954e+02,
           -1.14977979e+03, -1.74735596e+03,  4.88830933e+02,  5.99290100e+02,
            9.12052673e+02,  7.99225159e+02,  2.15954541e+03, -1.09067920e+03,
            8.91225098e+02, -6.90867676e+02, -1.16549402e+03, -4.88088745e+02,
            2.55402930e+03,  3.29889557e+02, -2.25736649e+02,  1.025

In [2]:
import math
import os

import arviz as az
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
from IPython.display import Image, set_matplotlib_formats
from matplotlib.patches import Ellipse, transforms

import jax.numpy as jnp
from jax import random, vmap
from jax.scipy.special import expit

import numpy as onp
import numpyro as numpyro
import numpyro.distributions as dist
from numpyro.diagnostics import effective_sample_size, print_summary
from numpyro.infer import MCMC, NUTS, Predictive

az.style.use("arviz-darkgrid")
numpyro.set_platform("cpu")
numpyro.set_host_device_count(4)
a = 3.5  # average morning wait time
b = -1  # average difference afternoon wait time
sigma_a = 1  # std dev in intercepts
sigma_b = 0.5  # std dev in slopes
rho = -0.7  # correlation between intercepts and slopes
Mu = jnp.array([a, b])
cov_ab = sigma_a * sigma_b * rho
Sigma = jnp.array([[sigma_a**2, cov_ab], [cov_ab, sigma_b**2]])

sigmas = jnp.array([sigma_a, sigma_b])  # standard deviations
Rho = jnp.array([[1, rho], [rho, 1]])  # correlation matrix

# now matrix multiply to get covariance matrix
Sigma = jnp.diag(sigmas) @ Rho @ jnp.diag(sigmas)
N_cafes = 20
seed = random.PRNGKey(5)  # used to replicate example
vary_effects = dist.MultivariateNormal(Mu, Sigma).sample(seed, (N_cafes,))
a_cafe = vary_effects[:, 0]
b_cafe = vary_effects[:, 1]
seed = random.PRNGKey(22)
N_visits = 10
afternoon = jnp.tile(jnp.arange(2), N_visits * N_cafes // 2)
cafe_id = jnp.repeat(jnp.arange(N_cafes), N_visits)
mu = a_cafe[cafe_id] + b_cafe[cafe_id] * afternoon
sigma = 0.5  # std dev within cafes
wait = dist.Normal(mu, sigma).sample(seed)
d = pd.DataFrame(dict(cafe=cafe_id, afternoon=afternoon, wait=wait))

/home/sosa/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


In [ ]:
import time as tm
cafe_id = jnp.array(d.cafe.values)
def model(cafe, afternoon, wait):
    a = numpyro.sample("a", dist.Normal(5, 2))
    b = numpyro.sample("b", dist.Normal(-1, 0.5))
    sigma_cafe = numpyro.sample("sigma_cafe", dist.Exponential(1).expand([2]))
    sigma = numpyro.sample("sigma", dist.Exponential(1))
    Rho = numpyro.sample("Rho", dist.LKJ(2, 2))
    cov = jnp.outer(sigma_cafe, sigma_cafe) * Rho
    a_cafe_b_cafe = numpyro.sample(
        "a_cafe,b_cafe", dist.MultivariateNormal(jnp.stack([a, b]), cov).expand([20])
    )
    a_cafe, b_cafe = a_cafe_b_cafe[:, 0], a_cafe_b_cafe[:, 1]
    print(b_cafe[cafe])
    mu = a_cafe[cafe] + b_cafe[cafe] * afternoon
    numpyro.sample("wait", dist.Normal(mu, sigma), obs=wait)
model(cafe_id, afternoon, jnp.array(d.wait.values))

In [4]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions
import numpy as np
import pandas as pd
N_cafes = 20
a = 3.5  # average morning wait time
b = -1  # average difference afternoon wait time
sigma_a = 1  # std dev in intercepts
sigma_b = 0.5  # std dev in slopes
rho = -0.7  # correlation between intercepts and slopes
Mu = tf.constant([a, b])
cov_ab = sigma_a * sigma_b * rho
Sigma = tf.constant([[sigma_a ** 2, cov_ab], [cov_ab, sigma_b ** 2]])
sigmas = tf.constant([sigma_a, sigma_b])  # standard deviations
Rho = tf.constant([[1, rho], [rho, 1]])  # correlation matrix

# now matrix multiply to get covariance matrix
Sigma = tf.linalg.tensor_diag(sigmas) @ Rho @ tf.linalg.tensor_diag(sigmas)

Sigma
def build_vary_effects():
    _seed = 5
    tf.random.set_seed(_seed)

    seed = tfp.util.SeedStream(_seed, salt="vary_effects")

    Mu = tf.constant([a, b])

    vary_effects = tfd.MultivariateNormalTriL(
        loc=Mu, scale_tril=tf.linalg.cholesky(Sigma)
    ).sample((N_cafes,), seed=seed())

    return vary_effects


vary_effects = build_vary_effects()

a_cafe = vary_effects[:, 0]
b_cafe = vary_effects[:, 1]
N_visits = 10
afternoon = np.tile(np.arange(2), N_visits * N_cafes // 2)
cafe_id = np.repeat(np.arange(N_cafes), N_visits)


def generate_data_frame():
    sigma = 0.5  # std dev within cafes

    _seed = 22
    tf.random.set_seed(_seed)

    seed = tfp.util.SeedStream(_seed, salt="generate_data_frame")

    mu = tf.gather(a_cafe, cafe_id) + tf.gather(b_cafe, cafe_id) * afternoon

    wait = tfd.Normal(loc=mu, scale=sigma).sample(seed=seed())
    d = pd.DataFrame(dict(cafe=cafe_id, afternoon=afternoon, wait=wait))

    return d


d = generate_data_frame()

In [37]:
import os
import re
import jax
Ncores = os.cpu_count()    
xla_flags = os.getenv("XLA_FLAGS", "")
xla_flags = re.sub(r"--xla_force_host_platform_device_count=\S+", "", xla_flags).split()
os.environ["XLA_FLAGS"] = " ".join(["--xla_force_host_platform_device_count={}".format(Ncores)] + xla_flags)
print('jax.local_device_count ',jax.local_device_count(backend=None))
from generated_functions import*
cafe = jnp.array(d.cafe.values)
afternoon = jnp.array(d.afternoon.values)
wait = jnp.array(d.wait.values)

init_key, sample_key = random.split(random.PRNGKey(int(r.randint(0, 10000000))))
init_key = jnp.array(init_key)

@jit
def jax_LinearOperatorDiag(s, cov):    
    def multiply_with_s(a):
        return jnp.multiply(a, s)
    vectorized_multiply = vmap(multiply_with_s)
    return jnp.transpose(vectorized_multiply(cov))


def model():
    a = yield normal(1, 5, 2)
    b = yield normal(1, -1, 0.5)
    sigma_cafe = yield exponential(2, 1)
    sigma = yield exponential(1, 1)
    rho = yield lkj((), 2, 2)
    a_cafe_b_cafe = yield multivariatenormaltril(N_cafes, jnp.concatenate([a,b]), jax_LinearOperatorDiag(sigma_cafe, rho))
    mu = a_cafe_b_cafe[:, 0][cafe] +  a_cafe_b_cafe[:, 1][cafe] * afternoon
    y = yield Independent(Normal(mu, sigma))
    
tensor = JointDistributionCoroutineAutoBatched(model)

jax.local_device_count  32


In [71]:
init_params

[Array([3.4546597], dtype=float32),
 Array([-0.24745472], dtype=float32),
 Array([0.73393834, 3.7439718 ], dtype=float32),
 Array([0.10379245], dtype=float32),
 Array([[ 1.        , -0.48375353],
        [-0.48375353,  1.        ]], dtype=float32),
 Array([[ 4.5433025 , -1.4463906 ],
        [ 2.409135  , -3.1256952 ],
        [ 2.4117396 ,  0.17069174],
        [ 3.8825395 ,  1.5221831 ],
        [ 2.8445044 , 12.678833  ],
        [ 3.9465768 , -7.089362  ],
        [ 3.7777708 ,  2.7931075 ],
        [ 1.9723744 ,  4.6654067 ],
        [ 2.942348  , -1.2520821 ],
        [ 2.9606543 ,  1.4972082 ],
        [ 3.7153726 , -0.9360685 ],
        [ 2.5986958 , 10.558637  ],
        [ 3.3644547 , -3.0091937 ],
        [ 3.1064672 ,  5.7687573 ],
        [ 4.417675  , -4.533324  ],
        [ 4.871417  , -0.8105924 ],
        [ 3.495174  , -5.119223  ],
        [ 2.931318  ,  0.9195129 ],
        [ 4.8179026 , -6.0424337 ],
        [ 2.6771631 ,  6.3740478 ]], dtype=float32)]

In [76]:
tf.eye(2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [ ]:

init_params2 = []
init_params2.append(jnp.array(tf.ones_like(init_params[0])))
init_params2.append(jnp.array(tf.ones_like(init_params[1])))
init_params2.append(jnp.array(tf.ones_like(init_params[2])))
init_params2.append(jnp.array(tf.ones_like(init_params[3])))
init_params2.append(jnp.array(tf.eye(2)))
init_params2.append(jnp.array(tf.ones_like(init_params[5])))


In [81]:
from functools import partial
import time as tm
@partial(jit, static_argnums=1)
def init_params(tensor, remove):
    init_key, sample_key = random.split(random.PRNGKey(0))
    init = list(tensor.sample(seed=jnp.array(init_key, dtype=jnp.uint32)))
    init.pop(remove)
    return init

init_params = init_params(tensor, 6)
init_params2 = []
init_params2.append(jnp.array(tf.ones_like(init_params[0])))
init_params2.append(jnp.array(tf.ones_like(init_params[1])))
init_params2.append(jnp.array(tf.ones_like(init_params[2])))
init_params2.append(jnp.array(tf.ones_like(init_params[3])))
init_params2.append(jnp.array(tf.eye(2)))
init_params2.append(jnp.array(tf.ones_like(init_params[5])))

def trace_fn(_, pkr): 
    return (
        pkr.target_log_prob,
        pkr.log_accept_ratio,
        pkr.has_divergence,
        pkr.energy
    )

def target_log_prob(*params):
  return tensor.log_prob(params + (wait,))

@jit
def run_chain(key):
    kernel = tfp.mcmc.NoUTurnSampler(target_log_prob, 1e-3)
    return tfp.mcmc.sample_chain(2000,
        current_state= init_params2,
        kernel=kernel,
        trace_fn=trace_fn,
        num_burnin_steps=500,
        parallel_iterations = 10,
        seed=key)
start = tm.time()  
rng_keys = jax.random.split(random.PRNGKey(0), 4)
result =  jax.pmap(run_chain)(rng_keys)
end = tm.time()    
print(f"HonnorMode took: {end - start:.4f} seconds")
posterior, sample_stats = result


/home/sosa/.local/lib/python3.10/site-packages/tensorflow_probability/python/internal/backend/jax/random_generators.py:283: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in zeros is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  minval = minval + np.zeros([1] * final_rank, dtype=dtype)
/home/sosa/.local/lib/python3.10/site-packages/tensorflow_probability/python/internal/backend/jax/random_generators.py:284: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'>  is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  return jaxrand.randint(key=seed, shape=shape, minval=minval, maxval=maxv

HonnorMode took: 1.9787 seconds


In [79]:
import arviz as az
p = dict(zip(tensor._flat_resolve_names(), posterior))
def tfp_trace_to_arviz(posterior, 
                       sample_stats,
                       var_names=None, 
                       sample_stats_name=['target_log_prob','log_accept_ratio','has_divergence','energy']):
    sample_stats = {k:jnp.transpose(v) for k, v in zip(sample_stats_name, sample_stats)}
    trace = {}
    for name, samp in zip(var_names, posterior):
        if len(samp.shape) == 2:
            transposed_shape = [1, 0]
        elif len(samp.shape) == 3:
            transposed_shape = [1, 0, 2]
        else:
            transposed_shape = [1, 0, 2, 3]
        trace[name] = tf.transpose(samp, transposed_shape)
    trace = az.from_dict(posterior=trace, sample_stats=sample_stats)
    return trace



trace = tfp_trace_to_arviz(posterior = posterior, sample_stats = sample_stats, var_names = ['alpha', 'beta', 'sigma_cafe', 'sigma', 'rho', 'a_cafe_b_cafe'])


/home/sosa/.local/lib/python3.10/site-packages/arviz/data/base.py:221: UserWarning: More chains (2000) than draws (4). Passed array should have shape (chains, draws, *shape)
  warnings.warn(


In [31]:
import time as tm
import stan
import nest_asyncio
import httpstan.models
import httpstan.cache
try:
  httpstan.cache.delete_model_directory(httpstan.models.calculate_model_name(stan_code)) # Delete  model in cache
except:
  pass

nest_asyncio.apply()
stan_code = """ 
data{
    vector[200] wait;
    array[200] int afternoon;
    array[200] int cafe;
}
parameters{
    vector[20] b_cafe;
    vector[20] a_cafe;
    real a;
    real b;
    vector<lower=0>[2] sigma_cafe;
    real<lower=0> sigma;
    corr_matrix[2] Rho;
}
model{
    vector[200] mu;
    Rho ~ lkj_corr( 2 );
    sigma ~ exponential( 1 );
    sigma_cafe ~ exponential( 1 );
    b ~ normal( -1 , 0.5 );    
    a ~ normal( 5 , 2 );
    {
        array[20] vector[2] YY;
        vector[2] MU;
        MU = [ a , b ]';
        for ( j in 1:20 ) YY[j] = [ a_cafe[j] , b_cafe[j] ]';
        YY ~ multi_normal( MU , quad_form_diag(Rho , sigma_cafe) );
    }
    for ( i in 1:200 ) {
        mu[i] = a_cafe[cafe[i]] + b_cafe[cafe[i]] * afternoon[i];        
    }
    
    wait ~ normal( mu , sigma );

}
"""
data = {
    'wait' : d['wait'].values.astype(float),
    'afternoon' : d['afternoon'].values.astype(int),
    'cafe' : d['cafe'].values.astype(int)+1,
}
start = tm.time()
stan_model = stan.build(stan_code, data = data)
fit = stan_model.sample(num_chains=4, num_samples=2000, num_warmup = 500)
end = tm.time()    
df = fit.to_frame()
print(f"Pystan took: {end - start:.4f} seconds")

Building...



Building: 24.3s, done.Messages from stanc:
Warning in '/tmp/httpstan_kziqn6tn/model_y5f2lzzr.stan', line 18, column 4: It
    is suggested to reparameterize your model to replace lkj_corr with
    lkj_corr_cholesky, the Cholesky factor variant. lkj_corr tends to run
    slower, consume more memory, and has higher risk of numerical errors.
    provided, or the prior(s) depend on data variables. In the later case,
    this may be a false positive.
    provided, or the prior(s) depend on data variables. In the later case,
    this may be a false positive.
Sampling:   0%/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()

Sampling:  25% (2500/10000)
Sampling:  50% (5000/10000)
Sampling:  75% (7500/10000)
Sampling: 100% (10000/10000)
Sampling: 100% (10000/10000), done.
Messages received during sampling:
  Gradien

Pystan took: 27.5516 seconds


In [80]:
pd.DataFrame(
    {
        "tfp": az.summary(trace,round_to='none')['mean'],
        "pystan": [df['a'].mean(),df['b'].mean(),
                   df['sigma_cafe.1'].mean(),
                   df['sigma_cafe.2'].mean(),   
                   df['sigma'].mean(),                
                   df['Rho.1.1'].mean(),df['Rho.2.1'].mean(),
                   df['Rho.1.2'].mean(),df['Rho.2.2'].mean(),                   
                   df['a_cafe.1'].mean(), df['b_cafe.1'].mean(),
                   df['a_cafe.2'].mean(), df['b_cafe.2'].mean(),
                   df['a_cafe.3'].mean(), df['b_cafe.3'].mean(),
                   df['a_cafe.4'].mean(), df['b_cafe.4'].mean(),
                   df['a_cafe.5'].mean(), df['b_cafe.5'].mean(),
                   df['a_cafe.6'].mean(), df['b_cafe.6'].mean(),
                   df['a_cafe.7'].mean(), df['b_cafe.7'].mean(),
                   df['a_cafe.8'].mean(), df['b_cafe.8'].mean(),
                   df['a_cafe.9'].mean(), df['b_cafe.9'].mean(),
                   df['a_cafe.10'].mean(), df['b_cafe.10'].mean(),
                   df['a_cafe.11'].mean(), df['b_cafe.11'].mean(),
                   df['a_cafe.12'].mean(), df['b_cafe.12'].mean(),
                   df['a_cafe.13'].mean(), df['b_cafe.13'].mean(),
                   df['a_cafe.14'].mean(), df['b_cafe.14'].mean(),
                   df['a_cafe.15'].mean(), df['b_cafe.15'].mean(),
                   df['a_cafe.16'].mean(), df['b_cafe.16'].mean(),
                   df['a_cafe.17'].mean(), df['b_cafe.17'].mean(),
                   df['a_cafe.18'].mean(), df['b_cafe.18'].mean(),
                   df['a_cafe.19'].mean(), df['b_cafe.19'].mean(),
                   df['a_cafe.20'].mean(), df['b_cafe.20'].mean(),
                   ]
    })

tfp    pystan
alpha[0]               3.679906  3.676953
beta[0]               -1.047126 -1.045073
sigma_cafe[0]          0.180061  1.008454
sigma_cafe[1]          0.032513  0.633495
sigma[0]               0.499404  0.498925
rho[0, 0]             16.831242  1.000000
rho[0, 1]            -21.672058 -0.636803
rho[1, 0]             31.480253 -0.636803
rho[1, 1]             17.490580  1.000000
a_cafe_b_cafe[0, 0]    3.023294  3.030511
a_cafe_b_cafe[0, 1]   -0.950339 -0.970327
a_cafe_b_cafe[1, 0]    3.100387  3.106751
a_cafe_b_cafe[1, 1]   -0.576176 -0.581565
a_cafe_b_cafe[2, 0]    5.417605  5.391189
a_cafe_b_cafe[2, 1]   -1.766814 -1.714900
a_cafe_b_cafe[3, 0]    3.716179  3.715676
a_cafe_b_cafe[3, 1]   -1.104432 -1.106009
a_cafe_b_cafe[4, 0]    3.619090  3.619345
a_cafe_b_cafe[4, 1]   -0.987458 -0.984966
a_cafe_b_cafe[5, 0]    4.007306  3.998718
a_cafe_b_cafe[5, 1]   -1.417969 -1.414143
a_cafe_b_cafe[6, 0]    2.946201  2.961904
a_cafe_b_cafe[6, 1]   -1.036769 -1.071148
a_cafe_b_cafe[7, 0]    3.273089  3.268399
a_cafe_b_cafe[7, 1]   -1.548673 -1.571130
a_cafe_b_cafe[8, 0]    4.079142  4.070478
a_cafe_b_cafe[8, 1]   -0.535414 -0.494864
a_cafe_b_cafe[9, 0]    5.379828  5.357812
a_cafe_b_cafe[9, 1]   -1.583972 -1.527031
a_cafe_b_cafe[10, 0]   5.441957  5.411571
a_cafe_b_cafe[10, 1]  -2.230138 -2.185735
a_cafe_b_cafe[11, 0]   2.818310  2.825429
a_cafe_b_cafe[11, 1]  -0.724233 -0.743570
a_cafe_b_cafe[12, 0]   3.200917  3.202582
a_cafe_b_cafe[12, 1]  -1.313965 -1.336699
a_cafe_b_cafe[13, 0]   4.484490  4.466324
a_cafe_b_cafe[13, 1]  -1.644005 -1.622906
a_cafe_b_cafe[14, 0]   3.662827  3.661274
a_cafe_b_cafe[14, 1]  -0.763882 -0.753785
a_cafe_b_cafe[15, 0]   3.614687  3.616477
a_cafe_b_cafe[15, 1]  -0.811974 -0.808960
a_cafe_b_cafe[16, 0]   2.565789  2.588126
a_cafe_b_cafe[16, 1]   0.132947  0.115627
a_cafe_b_cafe[17, 0]   1.573789  1.613336
a_cafe_b_cafe[17, 1]   0.074685  0.011671
a_cafe_b_cafe[18, 0]   4.276095  4.262892
a_cafe_b_cafe[18, 1]  -1.100084 -1.069385
a_cafe_b_cafe[19, 0]   3.137397  3.148290
a_cafe_b_cafe[19, 1]  -0.961415 -0.992030