Restarted Python 3.10.12

In [1]:
from  main import *
formula = dict(main = 'y~Normal(m,s)',
            likelihood = 'm ~  alpha + beta',
            prior1 = 's~Exponential(1)',
            prior2 = 'alpha ~ Normal(0,1)',
            prior3 = 'beta ~ Normal(0,1)',
            
            main1 = 'z~Normal(m2,s2)',
            likelihood2 = 'm2 ~ alpha2 + beta2',
            prior4 = 's2~Exponential(1)',
            prior5 = 'alpha2 ~ Normal(0,1)',
            prior6 = 'beta2 ~ Normal(0,1)') 
m = model(formula= formula)
m.sample(10)
m.tensor

2024-01-31 09:02:40.870748: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-31 09:02:40.889589: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-31 09:02:40.889605: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-31 09:02:40.890081: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-31 09:02:40.893542: I tensorflow/core/platform/cpu_feature_guar

<tfp.distributions.JointDistributionNamed 'JointDistributionNamed' batch_shape={alpha: [], alpha2: [], beta: [], beta2: [], s: [], s2: [], y: [], z: []} event_shape={alpha: [1], alpha2: [1], beta: [1], beta2: [1], s: [1], s2: [1], y: [1], z: [1]} dtype={alpha: float32, alpha2: float32, beta: float32, beta2: float32, s: float32, s2: float32, y: float32, z: float32}>

In [2]:
m.sample(10)

{'s2': <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[1.0119815 ],
        [0.5368687 ],
        [0.23798797],
        [2.6394184 ],
        [2.2930307 ],
        [2.3857243 ],
        [0.48907256],
        [0.26716697],
        [0.6238974 ],
        [0.16057445]], dtype=float32)>,
 'beta2': <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 0.6270838 ],
        [ 0.29314154],
        [-0.5856371 ],
        [-0.0296457 ],
        [-0.640067  ],
        [-1.3967685 ],
        [-1.2488045 ],
        [-0.09988479],
        [-1.0685792 ],
        [ 0.80748993]], dtype=float32)>,
 'alpha2': <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 1.4661463 ],
        [-0.33613828],
        [-1.8053781 ],
        [-0.3145417 ],
        [-0.5770143 ],
        [-0.96876055],
        [ 0.01727881],
        [-1.6199218 ],
        [ 1.3211194 ],
        [ 0.30712003]], dtype=float32)>,
 'z': <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 2.258665  ],
        [-0.5