In [1]:
import os
import sys
newPath = os.path.dirname(os.path.abspath(""))
if newPath not in sys.path:
    sys.path.append(newPath)

from main import *
m = bi(platform='cpu')

c:\Users\SSosa\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


jax.local_device_count 16


#  Random Cluster Assignment
We generate a brain with random clusters to simulate structures

In [7]:
import jax.numpy as jnp
import jax

def rand_cl(grid_size = (10, 10), block_size = 3):
    grid_size = (10, 10)
    block_size = 3

    # Calculate number of blocks along each dimension (round up to cover the whole grid)
    num_blocks_x = (grid_size[0] + block_size - 1) // block_size
    num_blocks_y = (grid_size[1] + block_size - 1) // block_size

    # Assign random values to each block
    key = jax.random.PRNGKey(0)
    block_values = jax.random.randint(key, (num_blocks_x, num_blocks_y), 0, 10)

    # Expand the block values into a grid
    array = jnp.kron(block_values, jnp.ones((block_size, block_size)))

    # Crop to desired grid size
    array = array[:grid_size[0], :grid_size[1]]

    return array

brain = jnp.zeros((10, 10, 5)) # 10 by 10 array on 5 layers

for i in range(brain.shape[2]):
    brain = brain.at[:,:, i].set(rand_cl(brain.shape[:1]))
brain

Array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
    

In [19]:
import jax.numpy as jnp
import jax

def rand_cl_3d(grid_size=(10, 10, 5), block_size=3,seed=0):
    # Extract each dimension size
    size_x, size_y, size_z = grid_size
    
    # Calculate number of blocks along each spatial dimension
    num_blocks_x = (size_x + block_size - 1) // block_size
    num_blocks_y = (size_y + block_size - 1) // block_size
    
    # Generate random block values for each layer
    key = jax.random.PRNGKey(seed)
    block_values = jax.random.randint(
        key, (num_blocks_x, num_blocks_y, size_z), 0, 10
    )
    
    # Expand each layer's block values
    expanded = jnp.repeat(
        jnp.repeat(block_values, block_size, axis=0), 
        block_size, axis=1
    )
    
    # Crop to the desired grid size
    array = expanded[:size_x, :size_y, :]
    
    return array

brain = rand_cl_3d()
brain

Array([[[7, 3, 4, 4, 4],
        [7, 3, 4, 4, 4],
        [7, 3, 4, 4, 4],
        [0, 7, 4, 5, 6],
        [0, 7, 4, 5, 6],
        [0, 7, 4, 5, 6],
        [6, 7, 1, 3, 7],
        [6, 7, 1, 3, 7],
        [6, 7, 1, 3, 7],
        [7, 8, 2, 2, 2]],

       [[7, 3, 4, 4, 4],
        [7, 3, 4, 4, 4],
        [7, 3, 4, 4, 4],
        [0, 7, 4, 5, 6],
        [0, 7, 4, 5, 6],
        [0, 7, 4, 5, 6],
        [6, 7, 1, 3, 7],
        [6, 7, 1, 3, 7],
        [6, 7, 1, 3, 7],
        [7, 8, 2, 2, 2]],

       [[7, 3, 4, 4, 4],
        [7, 3, 4, 4, 4],
        [7, 3, 4, 4, 4],
        [0, 7, 4, 5, 6],
        [0, 7, 4, 5, 6],
        [0, 7, 4, 5, 6],
        [6, 7, 1, 3, 7],
        [6, 7, 1, 3, 7],
        [6, 7, 1, 3, 7],
        [7, 8, 2, 2, 2]],

       [[7, 5, 9, 1, 8],
        [7, 5, 9, 1, 8],
        [7, 5, 9, 1, 8],
        [0, 2, 2, 3, 4],
        [0, 2, 2, 3, 4],
        [0, 2, 2, 3, 4],
        [8, 4, 3, 9, 2],
        [8, 4, 3, 9, 2],
        [8, 4, 3, 9, 2],
        [0, 4, 3, 0

# Define effect of categories on brain clusters



We need create N data points by generating categories effect in privous section and only one categorie per data point

In [29]:
Ncat=len(jnp.unique(brain))
N = 100
backup=brain
brains=[]
categories=[]
intercept= 210
coefs=bi.dist.normal(0,1,shape=(Ncat,),sample=True)
for i in range(N):
    # sample a category
    category = np.random.randint(1, Ncat)
    categories.append(category)
    tmp=brain.copy()
    tmp= tmp.at[jnp.where(tmp==category)].set(
        bi.dist.normal(intercept, 10, sample=True,shape=tmp[jnp.where(tmp==category)].shape)+
        bi.dist.normal(coefs[category-1] * i+1, 1, sample=True,shape=tmp[jnp.where(tmp==category)].shape)
        ) 
    tmp= tmp.at[jnp.where(tmp!=category)].set(
        bi.dist.normal(intercept, 10, sample=True,shape=tmp[jnp.where(tmp!=category)].shape)
        )
    brains.append(tmp)
    
brains=jnp.array(brains)

c:\Users\SSosa\AppData\Local\Programs\Python\Python312\Lib\site-packages\jax\_src\ops\scatter.py:92: FutureWarning:

scatter inputs have incompatible types: cannot safely cast value from dtype=float64 to dtype=int32 with jax_numpy_dtype_promotion='standard'. In future JAX releases this will result in an error.



In [77]:
array_3d

Array([[[194, 204, 208, 203, 216],
        [212, 217, 220, 227, 220],
        [221, 210, 209, 196, 212],
        [205, 208, 216, 200, 205],
        [212, 217, 201, 204, 217],
        [204, 221, 203, 214, 217],
        [213, 212, 208, 207, 215],
        [197, 197, 210, 222, 204],
        [210, 193, 192, 214, 200],
        [197, 203, 179, 213, 217]],

       [[199, 220, 226, 189, 236],
        [206, 225, 217, 207, 220],
        [206, 217, 192, 211, 217],
        [196, 207, 222, 204, 204],
        [209, 212, 200, 214, 204],
        [213, 220, 215, 211, 211],
        [206, 212, 215, 217, 209],
        [202, 211, 201, 204, 217],
        [197, 203, 215, 217, 195],
        [207, 211, 202, 207, 218]],

       [[212, 222, 199, 200, 224],
        [214, 202, 217, 218, 198],
        [213, 204, 203, 214, 207],
        [219, 217, 207, 200, 226],
        [202, 218, 208, 201, 206],
        [223, 220, 209, 211, 216],
        [216, 235, 203, 207, 209],
        [204, 226, 222, 201, 226],
        [207, 19

In [75]:
import plotly.graph_objects as go
import numpy as np

# Simulating your 3D data
array_3d =brains[0,:,:,:]

# Create a Volume plot
fig = go.Figure(data=[go.Volume(
    x=np.arange(array_3d.shape[0]).repeat(array_3d.shape[1] * array_3d.shape[2]),
    y=np.tile(np.arange(array_3d.shape[1]).repeat(array_3d.shape[2]), array_3d.shape[0]),
    z=np.tile(np.arange(array_3d.shape[2]), array_3d.shape[0] * array_3d.shape[1]),
    value=array_3d.flatten(),
    isomin=int(array_3d.min()),
    isomax=int(array_3d.max()),
    colorscale='Gray',
    opacity=0.1,
    surface_count=10,
)])

fig.update_layout(
    title="3D Volume Plot",
    scene=dict(
        xaxis_title='X',
        yaxis_title='Y',
        zaxis_title='Z'),
    width=800,
    height=800
)

fig.show()


# Convultion

In [1]:
import jax
import jax.numpy as jnp
import jax.nn 


In [32]:
x=jnp.linspace(0, 10, 20)
window = jnp.ones(10) / 10
y=jnp.convolve(x, window, mode='same')
y


Array([0.5263158, 0.7894738, 1.1052632, 1.4736843, 1.894737 , 2.368421 ,
       2.894737 , 3.4210527, 3.9473686, 4.4736843, 5.       , 5.5263157,
       6.052632 , 6.578948 , 7.105263 , 7.6315794, 7.1052637, 6.5263157,
       5.8947372, 5.2105265], dtype=float32)

The convolution operation here slides the window over x and at each step computes a weighted sum. In formula form, for each output index k:

$$
y[k] = \sum_{i=0}^{N-1} windows[i] \cdot x[k-offset+i]
$$

Because our window has length 10 (an even number), many libraries (including JAX’s implementation, similar to NumPy’s) choose an offset of 5. This means that for a given output index k, the convolution tries to use the input values from indices:

$$
k−5,k−5+1,…,k+4.
$$


In [40]:
y=jax.nn.relu(y)
y = y[jnp.newaxis, jnp.newaxis, :, jnp.newaxis]
y

Array([[[[0.5263158],
         [0.7894738],
         [1.1052632],
         [1.4736843],
         [1.894737 ],
         [2.368421 ],
         [2.894737 ],
         [3.4210527],
         [3.9473686],
         [4.4736843],
         [5.       ],
         [5.5263157],
         [6.052632 ],
         [6.578948 ],
         [7.105263 ],
         [7.6315794],
         [7.1052637],
         [6.5263157],
         [5.8947372],
         [5.2105265]]]], dtype=float32)

In [41]:
import flax
flax.linen.avg_pool(y, window_shape=(2, 2), strides=(2, 2), padding='VALID')

Array([], shape=(1, 0, 10, 1), dtype=float32)