In [1]:
import os
import sys
newPath = os.path.dirname(os.path.abspath(""))
if newPath not in sys.path:
    sys.path.append(newPath)

from main import *
m = bi(platform='cpu')

jax.local_device_count 16


c:\Users\SSosa\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
brain = jnp.zeros((10, 10, 5)) # 10 by 10 array on 5 layers
m = bi(platform='cpu')


jax.local_device_count 16


Array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=float64)

In [ ]:
m.dist.categorical(probs=jnp.array([0.1, 0.2, 0.3, 0.4, 0.5]), shape=(,),sample=True)

Array([2, 3, 3, 2, 2], dtype=int64)

#  Random Cluster Assignment
We generate a brain with random clusters to simulate structures

In [185]:
import jax.numpy as jnp
import jax

def rand_cl(grid_size = (10, 10), block_size = 3):
    grid_size = (10, 10)
    block_size = 3

    # Calculate number of blocks along each dimension (round up to cover the whole grid)
    num_blocks_x = (grid_size[0] + block_size - 1) // block_size
    num_blocks_y = (grid_size[1] + block_size - 1) // block_size

    # Assign random values to each block
    key = jax.random.PRNGKey(0)
    block_values = jax.random.randint(key, (num_blocks_x, num_blocks_y), 0, 10)

    # Expand the block values into a grid
    array = jnp.kron(block_values, jnp.ones((block_size, block_size)))

    # Crop to desired grid size
    array = array[:grid_size[0], :grid_size[1]]

    return array

brain = jnp.zeros((10, 10, 5)) # 10 by 10 array on 5 layers

for i in range(brain.shape[2]):
    brain = brain.at[:,:, i].set(rand_cl(brain.shape[:1]))
brain

Array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
    

# Define effect of categories on brain clusters



We need create N data points by generating categories effect in privous section and only one categorie per data point

In [186]:
brain

Array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
    

In [190]:
N = 100
backup=brain
brains=[]
categories=[]
for i in range(N):
    # sample a category
    category = np.random.randint(1, Ncat)
    categories.append(category)
    tmp=brain.copy()
    tmp= tmp.at[jnp.where(tmp==category)].set(bi.dist.normal(coefs[category-1] * i+1, 1, sample=True,shape=tmp[jnp.where(tmp==category)].shape)) 
    brains.append(tmp)
brains=jnp.array(brains)

# TODO: The main issue is that except for brain region that are not in category, their value is not random